### ISSUE TITLE
thinklmi -g BootOrder Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by traxtopel** [lenovo/thinklmi#3]
root:~# thinklmi -g BootOrder
USBCD:USBFDD:NVMe0:NVMe1:HDD0:HDD1:USBHDD:PXEBOOT::LENOVOCLOUD
HDD0,HDD1,HDD2,HDD3,HDD4,PXEBOOT,ATAPICD0,ATAPICD1,ATAPICD2,USBFDD,USBCD,USBHDD,OtherHDD,OtherCD,NVMe0,NVMe1,LENOVOCLOUD,NODEV
**Segmentation fault (core dumped)**

RHEL 8.2
4.18.0-193.6.3.el8_2.x86_64

What information do you require?

**Comment by mrhpearson** [comment]
Thanks - I can reproduce so nothing extra needed. I'll looking into it

**Comment by mrhpearson** [comment]
It's a string overflow issue as the result gets returned from the kernel driver (allocated size 190) into the user space where only 128 is allocated. :(

**Comment by mrhpearson** [comment]
Fixed with https://github.com/lenovo/thinklmi/commit/d5c2f51f9c414bc3f91189fec07df3b0b30c79e4
I increased the buffer size from 128 to 512 so the BootOrder output doesn't overflow or get truncated any more. I think the Boot order is the worst case item but I'll do a bit more checking to be sure.

Also added a check so if something comes up in the future that overflows it will automatically get truncated and a warning issued instead of seg-faulting.

Thanks for the details.
Mark
